USE [master]
GO

/****** Object:  Database [dbHandsOn]    Script Date: 04/01/2018 17:52:05 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'dbHandsOn')
DROP DATABASE [dbHandsOn]
GO

USE [master]
GO

/****** Object:  Database [dbHandsOn]    Script Date: 04/01/2018 17:52:06 ******/
CREATE DATABASE [dbHandsOn] ON  PRIMARY 
( NAME = N'dbHandsOn', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\dbHandsOn.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbHandsOn_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\dbHandsOn_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbHandsOn] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbHandsOn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbHandsOn] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbHandsOn] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbHandsOn] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbHandsOn] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbHandsOn] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbHandsOn] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbHandsOn] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbHandsOn] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbHandsOn] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbHandsOn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbHandsOn] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbHandsOn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbHandsOn] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbHandsOn] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbHandsOn] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbHandsOn] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbHandsOn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbHandsOn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbHandsOn] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbHandsOn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbHandsOn] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbHandsOn] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbHandsOn] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbHandsOn] SET  READ_WRITE 
GO

ALTER DATABASE [dbHandsOn] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbHandsOn] SET  MULTI_USER 
GO

ALTER DATABASE [dbHandsOn] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbHandsOn] SET DB_CHAINING OFF 
GO


